name: Documentation bug
description: Raise an issue related to content.
title: "🐞 Documentation Bug: "
labels: "Documentation Bug"
body:
  - type: markdown
    attributes:
      value: |
        * Please check that there is not an existing open [issue](https://github.com/scaleway/docs-content/issues) before you create a new one.
        * Read the [writing guidelines](https://github.com/scaleway/docs-content/blob/main/docs/CONTRIBUTING.md#writing-guidelines) before you continue.
  - type: input
    attributes:
      label: Where on scaleway.com/en/docs did you see this issue?
      placeholder: https://www.scaleway.com/en/docs/
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the issue
      placeholder: "A clear and concise description of what the issue is"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: "Add any other context about the problem"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Related PR(s)
      placeholder: "Let us know if this is related to an open pull request"
    validations:
      required: false